feat: Controller now has to be provided as parameter so the selected …
Iconica-Development/flutter_date_time_picker pull request #41
Opened 2023-11-06 12:58 UTC by JacquesDIconica

…date can be changed from outside the widget.

2023-11-06 13:15 UTC, Gorter-dev requested changes

2023-11-06 13:15 UTC, Gorter-dev commented on lib/src/utils/date_time_picker_controller.dart
THIS AIN'T NO CONTROLLER

2023-11-06 13:19 UTC, freekvandeven commented on lib/src/utils/date_time_picker_controller.dart
!

2023-11-07 09:10 UTC, Gorter-dev approved these changes

2023-11-07 09:10 UTC, merged