added an overlay based date time picker
Iconica-Development/flutter_date_time_picker pull request #7
Opened 2022-11-17 12:59 UTC by BeingBright

## Describe your changes

## Checklist before requesting a review
- [ ] Test coverage is adequate
- [ ] Test makes sense
- [ ] Code is documented(all public methods)
- [ ] Code quality is adequate
- [ ] Feature complete
- [ ] (Almost no bugs)
- [ ] Dart analyzer completes without failure
- [ ] Changelog is updated
- [ ] Version is updated
- [ ] Readme is clean

## Why?
The reason why this pull-request is made is because the current date time picker does not work within the project 'Beep'.

2022-11-17 14:09 UTC, PureTryOut requested changes

2022-11-17 14:09 UTC, PureTryOut commented on lib/src/overlay_date_time_picker.dart
> +    _overlay = OverlayEntry(
Don't use `initState()` as a constructor when not actually setting state. You can assign the variable immediately when you're declaring it on line 88.

2022-11-17 14:09 UTC, PureTryOut commented on lib/src/overlay_date_time_picker.dart
> +    _dateTimePickerController = DateTimePickerController(
Same here, assign it immediately on line 89.

2022-11-17 14:09 UTC, PureTryOut commented on lib/src/widgets/overlay_date_time_picker/overlay.dart
> +        previousPage();
Why are you splitting this up into another function?

2022-11-17 14:09 UTC, PureTryOut commented on lib/src/widgets/overlay_date_time_picker/overlay.dart
> +        .then(
Any reason to prefer this over making the entire thing a regular `async` function and awaiting this?

2022-11-17 14:09 UTC, PureTryOut commented on lib/src/widgets/overlay_date_time_picker/overlay.dart
> +        .then(
Any reason to prefer this over making the entire thing a regular `async` function and awaiting this?

2022-11-17 14:09 UTC, PureTryOut commented on lib/src/widgets/overlay_date_time_picker/overlay.dart
> +        nextPage();
Why are you splitting this up into another function?

2022-11-17 14:09 UTC, PureTryOut commented on lib/src/widgets/overlay_date_time_picker/pickable_date.dart
> +  bool isWeekday(DateTime date) {
This is an unused function. If this is intended as a public API then please add documentation to it.

2022-11-17 15:45 UTC, PureTryOut approved these changes

2022-11-18 08:04 UTC, FlutterJoey approved these changes

2022-11-18 08:05 UTC, merged